image:
  registry: registry.gitlab.com
  image: ska-telescope/oso/ska-oso-slt-ui/ska-oso-slt-ui
  tag:  1.0.0-dev.c73f8ea39 # Defaults to chart's appVersion when empty
  pullPolicy: IfNotPresent

ingress:
  prependByNamespace: true
  path: slt
