apiVersion: v2
name: ska-oso-slt-ui-umbrella
description: Helm umbrella chart for Observation Design Tool application
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-oso-slt-ui
  version: 0.1.0
  repository: file://../ska-oso-slt-ui

# SLT services provides services required by the SLT UI
- name: ska-oso-slt-services-umbrella
  version: 0.2.1
  repository: https://artefact.skao.int/repository/helm-internal

