apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "ska-oso-slt-ui.labels" . | indent 4 }}
data:
  BACKEND_URL: {{ .Values.backendURL }}
  BASE_URL: /{{ .Release.Namespace }}/slt/
  REACT_APP_USE_LOCAL_DATA: {{ .Values.runtimeEnv.useLocalData | quote }}
